-- ============================================
-- POLLO REY — Esquema de Supabase
-- Ejecutar en SQL Editor de tu proyecto Supabase
-- ============================================

-- 1. Habilitar Row Level Security (opcional pero recomendado)
alter table if exists comments disable row level security;

-- 2. Crear tabla de comentarios
create table if not exists comments (
  id bigint generated by default as identity primary key,
  name text not null,
  comment text not null,
  rating smallint not null check (rating >= 1 and rating <= 5),
  created_at timestamptz not null default now()
);

-- 3. Crear índice para ordenar por fecha (más recientes primero)
create index if not exists idx_comments_created_at on comments (created_at desc);

-- 4. Permitir lectura anónima (SELECT) e insert (INSERT)
--    Ajusta según tu necesidad de seguridad
create policy "Permitir lectura a todos"
  on comments for select
  using (true);

create policy "Permitir inserción a todos"
  on comments for insert
  with check (true);

-- 5. (Opcional) Habilitar publicación en realtime
--    Ve a Project Settings > Realtime > y agrega la tabla "comments"
--    O ejecuta:
--    alter publication supabase_realtime add table comments;
